In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data_yelp = pd.read_csv("yelp_labelled.txt",sep='\t',header=None)

In [3]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [4]:
column_name = ['Review','Sentiment']
data_yelp.columns = column_name

In [5]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [6]:
data_yelp.shape

(1000, 2)

In [7]:
data_amazon = pd.read_csv('amazon_cells_labelled.txt',sep='\t',header=None)
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [8]:
data_amazon.columns = column_name

In [9]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [10]:
data_amazon.shape

(1000, 2)

In [11]:
data_imdb = pd.read_csv('imdb_labelled.txt',sep='\t',header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [12]:
data_imdb.columns = column_name

In [13]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [14]:
data_imdb.shape

(748, 2)

In [15]:
# Append all the data in a single dataframe

In [16]:
data = data_yelp.append([data_amazon,data_imdb],ignore_index=True)

C:\Users\PC\AppData\Local\Temp\ipykernel_19892\3996123729.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data_yelp.append([data_amazon,data_imdb],ignore_index=True)


In [17]:
data.shape

(2748, 2)

In [18]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [19]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [20]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [21]:
X = data['Review']
y = data['Sentiment']

In [22]:
# Data cleaning

In [23]:
import string

In [24]:
punct = string.punctuation

In [25]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [26]:
from spacy.lang.en.stop_words import STOP_WORDS

In [27]:
stopwords = list(STOP_WORDS)

In [29]:
stopwords

['the',
 '‘ll',
 'or',
 'not',
 '’d',
 '’m',
 'had',
 'put',
 'myself',
 'behind',
 'whose',
 'becomes',
 'seem',
 'wherever',
 'who',
 'their',
 'any',
 'never',
 'he',
 'eleven',
 'some',
 'hers',
 'whereby',
 'alone',
 'these',
 'whatever',
 'i',
 "'m",
 'latter',
 'besides',
 'beyond',
 'thence',
 'yet',
 'be',
 'do',
 'from',
 'might',
 'will',
 'without',
 "'ll",
 'at',
 'ten',
 'after',
 'once',
 "'s",
 'neither',
 'show',
 'each',
 'those',
 'whom',
 'very',
 'is',
 'ever',
 'into',
 'through',
 'an',
 'no',
 'his',
 'did',
 'when',
 'too',
 'see',
 'yours',
 'three',
 'four',
 'nor',
 'wherein',
 "'d",
 'above',
 'it',
 'whenever',
 'somehow',
 'via',
 'whence',
 'nine',
 'thru',
 'thereupon',
 'due',
 'part',
 'thereby',
 'made',
 'get',
 'moreover',
 'however',
 'ca',
 'anything',
 'such',
 'least',
 'were',
 'him',
 'everywhere',
 'elsewhere',
 'used',
 'go',
 'done',
 'she',
 'could',
 'say',
 'you',
 'herself',
 'therefore',
 'yourself',
 '‘ve',
 'would',
 'cannot',
 'oft

In [28]:
# creating function for data cleaning

In [32]:
import spacy
nlp = spacy.load('en_core_web_sm')

def text_data_cleaning(sentence):
    doc = nlp(sentence)
    tokens = []
    
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    
    return cleaned_tokens

In [33]:
# if root form of that word is not pronoun then it is going to convert that into lower form and if that word is a proper noun, then we are directly taking lower form, because there is no lemma.

In [34]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")

['hello', 'beautiful', 'day', 'outside']

In [35]:
# Vectorization Feature Engineering (TF-IDF)

In [36]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [37]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
# tokenizer=text_data_cleaning, tokenization will be done according to this function

In [38]:
classifier = LinearSVC()

In [39]:
# Train the Model

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [41]:
X_train.shape,X_test.shape

((2198,), (550,))

In [42]:
X_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

In [43]:
clf = Pipeline([('tfidf',tfidf),('clf',classifier)])
# it will first do vectorization and then it will do classification

In [44]:
clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x0000018763F2ACA0>)),
                ('clf', LinearSVC())])

In [45]:
# in this we don't need to prepare the dataset for testing(X_test)

In [46]:
# Predict the Test set results

In [48]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [49]:
y_pred = clf.predict(X_test)

In [50]:
confusion_matrix(y_test,y_pred)

array([[201,  78],
       [ 50, 221]], dtype=int64)

In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550


In [52]:
accuracy_score(y_test,y_pred)

0.7672727272727272

In [53]:
clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])

array([1], dtype=int64)

In [54]:
clf.predict(["It's hard to learn new things!"])

array([0], dtype=int64)